import React from 'react';
import HeroSection from '../AboutUsPage/components/HeroSection';
import StepsToOpenAccount from '../Deposit&WithdrawPage/components/StepsToOpenAccount';
import TradingComponent from '../LandingPage/components/TradingComponent';

const RiskPage = () => {
    return (
        <div>
            <HeroSection title="RISK DISCLOSURE" text="True ECN spreads from 0.0 Pips.

" />
            <div className=' footerLinkPage'>
                <div className="basicRow">
                    <div className="basicText">Prospective clients should study the following risk warnings very carefully. Please note that we do not explore or explain all the risks involved when dealing in Financial Instruments. We outline the general nature of the risks of dealing in Financial Instruments on a fair and non-misleading basis. In particular, Contracts for Difference ('CFDs') are complex financial products and not suitable for all investors. CFDs, are leveraged products that mature when you choose to close an existing open position. By investing in CFDs, you assume a high level of risk and can result in the loss of all of your invested capital.</div>
                    <div className="basicTitle">Acknowledgement</div>
                    <div className="basicText">. The Customer shall be responsible for the risks of financial losses caused by the failure of information, communication, electronic and other systems. The result of any system failure may be that his order is either not executed according to his instructions or it is not executed at all. The Company does not accept any liability in the case of such a failure.
<br/><br/>
2. While trading through the Client Terminal the Customer shall be responsible for the risks of financial losses caused by:
<br/>(a) customer's or Company's hardware or software failure, malfunction or misuse;
<br/>(b) poor Internet connection either on the side of the Customer or the Company or both, or interruptions or transmission blackouts or public electricity network failures or hacker attacks, overload of connection;
<br/>(c) the wrong settings in the Client Terminal;<br/>
(d) delayed Client Terminal updates;<br/>
(e) the Customer disregarding the applicable rules described in the Client Terminal user guide and in the Company's Website.
<br/><br/>
3. The Customer acknowledges that at times of excessive deal flow the Customer may have some difficulties to be connected over the telephone with a Dealer, especially in a Fast Market (for example, when key macroeconomic indicators are released). Abnormal Market Conditions
<br/><br/>
4. The Customer acknowledges that under Abnormal Market Conditions the period during which the Instructions and Requests are executed may be extended. Trading Platform
<br/><br/>
5. The Customer acknowledges that only one Request or Instruction is allowed to be in the queue at one time. Once the Customer has sent a Request or an Instruction, any further Requests or Instructions sent by the Customer are ignored and the "Order is locked" message appears until the first Request or Instruction is executed.
<br/><br/>
6. The Customer acknowledges that the only reliable source of Quotes Flow information is that of the real/live Server's Quotes Base. Quotes Base in the Client Terminal is not a reliable source of Quotes Flow information because the connection between the Client Terminal and the Server may be disrupted at some point and some of the Quotes simply may not reach the Client Terminal.
<br/><br/>
7. The Customer acknowledges that when the Customer closes the order placing/modifying/deleting window or the position opening/closing window, the Instruction or Request, which has been sent to the Server, shall not be cancelled.
<br/><br/>
8. In case the Customer has not received the result of the execution of the previously sent Instruction but decides to repeat the Instruction, the Customer shall accept the risk of making two Transactions instead of one, however the client may receive an "Order is locked" message as described in point 2.5 above.
<br/><br/>
9. The Customer acknowledges that if the Pending Order has already been executed but the Customer sends the Instruction to modify its level and the levels of If-Done Orders at the same time, the only Instruction, which will be executed, is the Instruction to modify Stop Loss and/or Take Profit levels on the position opened when the Pending Order triggered. Communication
<br/><br/>
10. The Customer shall accept the risk of any financial losses caused by the fact that the Customer has received with delay or has not received at all any notice from the Company.
<br/><br/>
11. The Customer acknowledges that the unencrypted information transmitted by email is not protected from any unauthorised access.
<br/><br/>
12. The Customer is fully responsible for the risks in respect of undelivered trading platform internal mail messages sent to the Customer by the Company as they are automatically deleted within 3 (three) calendar days .
<br/><br/>
13. The Customer is wholly responsible for the privacy of the information received from the Company and accepts the risk of any financial losses caused by the unauthorised access of a third party to the Customer's Trading Account.
<br/><br/>
14. The Company has no responsibility if authorized/unauthorised third persons have access to information, including electronic addresses, electronic communication and personal data, access data when the above are transmitted between the Company or any other party, using the internet or other network communication facilities, telephone, or any other electronic means. Force Majeure Event
<br/><br/>
15. In case of a Force Majeure Event the Customer shall accept the risk of financial losses.</div>
               <div className="basicTitle">Risk Warning Notice for Foreign Exchange and Derivative Products</div>
               <div className="basicText">. This notice cannot disclose all the risks and other significant aspects of foreign exchange and derivative products such as futures, options, and Contracts for Differences. You should not deal in these products unless you understand their nature and the extent of your exposure to risk. You should also be satisfied that the product is suitable for you in light of your circumstances and financial position. Certain strategies, such as a "spread" position or a "straddle", may be as risky as a simple Long or Short position. Although forex and derivative instruments can be used for the management of investment risk, some of these products are unsuitable for many investors. You should not engage in any dealings directly or indirectly in derivative products unless you know and understand the risks involved in them and that you may lose entirely all of your money. Different instruments involve different levels of exposure to risk and in deciding whether to trade in such instruments you should be aware of the following points: Effect of Leverage
               <br/><br/>
2. Under Margin Trading conditions even small market movements may have great impact on the Customer's Trading Account. It is important to note that all accounts trade under the effect of Leverage. The Customer must consider that if the market moves against the Customer, the Customer may sustain a total loss greater than the funds deposited. The Customer is responsible for all the risks, financial resources the Customer uses and for the chosen trading strategy. It is highly recommended that the Customer maintains a Margin Level (percentage Equity to Necessary Margin ratio which is calculated as Equity / Necessary Margin * 100%) of not lower than 1,000%. It is also recommended to place Stop Loss to limit potential losses, and Take Profit to collect profits, when it is not possible for the Customer to manage the Customer's Open Positions. The Customer shall be responsible for all financial losses caused by the opening of the position using temporary excess Free Margin on the Trading Account gained as a result of a profitable position (cancelled by the Company afterwards) opened at an Error Quote (Spike) or at a Quote received as a result of a Manifest Error. High Volatile Instruments
<br/><br/>
3. Some Instruments trade within wide intraday ranges with volatile price movements. Therefore, the Customer must carefully consider that there is a high risk of losses as well as profits. The price of Derivative financial instruments is derived from the price of the underlying asset in which the instruments refer to (for example currency, stock, metals, indices, etc). Derivative financial instruments and related markets can be highly volatile. The prices of instruments and the underlying asset may fluctuate rapidly and over wide ranges and may reflect unforeseeable events or changes in conditions, none of which can be controlled by the Customer or the Company. Under certain market conditions it may be impossible for a Customer's order to be executed at declared price leading to losses. The prices of instruments and the underlying asset will be influenced by, amongst other things, changing supply and demand relationships, governmental, agricultural, commercial and trade programs and policies, national and international political and economic events and the prevailing psychological characteristics of the relevant market place. Therefore, Stop Loss order cannot guarantee the limit of loss. The Customer acknowledges and accepts that, regardless of any information which may be offered by the Company, the value of Instruments may fluctuate downwards or upwards and it is even probable that the investment may become of no value. This is owed to the margining system applicable to such trades, which generally involves a comparatively modest deposit or margin in terms of the overall contract value, so that a relatively small movement in the underlying market can have a disproportionately dramatic effect on the Customer's trade. If the underlying market movement is in the Customer's favour, the Customer may achieve a good profit, but an equally small adverse market movement can not only quickly result in the loss of the Customers' entire deposit, but may also expose the Customer to a large additional loss. Liquidity
<br/><br/>
4. Some of the underlying assets may not become immediately liquid as a result of reduced demand for the underlying asset and Customer may not be able to obtain the information on the value of these or the extent of the associated risks. Futures 5. Transactions in futures involve the obligation to make, or to take, delivery of the underlying asset of the contract at a future date, or in some cases to settle the position with cash. They carry a high degree of risk. The gearing or leverage often obtainable in futures trading means that a small deposit or down payment can lead to large losses as well as gains. It also means that a relatively small movement can lead to a proportionately much larger movement in the value of your investment, and this can work against you as well as for you. Futures transactions have a contingent liability, and you should be aware of the implications of this, in particular the margining requirements, which are set out below. Options
<br/><br/>
6. There are many different types of options with different characteristics subject to the following conditions. Buying Options: Buying options involves less risk than selling options because, if the price of the underlying asset moves against you, you can simply allow the option to lapse. The maximum loss is limited to the premium, plus any commission or other transaction charges. However, if you buy a call option on a futures contract and you later exercise the option, you will acquire the future. This will expose you to the risks described under futures' and contingent liability investment transactions. Writing Options: If you write an option, the risk involved is considerably greater than buying options. You may be liable for margin to maintain your position and a loss may be sustained well in excess of the premium received. By writing an option, you accept a legal obligation to purchase or sell the underlying asset if the option is exercised against you, however far the market price has moved away from the exercise price. If you already own the underlying asset which you have contracted to sell (when the options will be known as covered call options) the risk is reduced. If you do not own the underlying asset (uncovered call options) the risk can be unlimited. Only experienced persons should contemplate writing uncovered options, and then only after securing full details of the applicable conditions and potential risk exposure. Contracts for Differences
<br/><br/>
7. The CFDs available for trading with the Company are non-deliverable spot transactions giving an opportunity to make profit on changes in currency rates, commodity, stock market indices or share prices called the underlying instrument. If the underlying instrument movement is in the Customer's favour, the Customer may achieve a good profit, but an equally small adverse market movement can not only quickly result in the loss of the Customers' entire deposit but also any additional commissions and other expenses incurred. So, the Customer must not enter into CFDs unless he is willing to undertake the risks of losing entirely all the money which he has invested and also any additional commissions and other expenses incurred. Investing in a Contract for Differences carries the same risks as investing in a future or an option and you should be aware of these as set out above. Transactions in Contracts for Differences may also have a contingent liability and you should be aware of the implications of this as set out below. Off-exchange Transactions in Derivatives
<br/><br/>
8. CFDs, forex and precious metals are off-exchange transactions. While some off-exchange markets are highly liquid, transactions in off-exchange or non-transferable derivatives may involve greater risk than investing in on-exchange derivatives because there is no exchange market on which to close out an Open Position. It may be impossible to liquidate an existing position, to assess the value of the position arising from an off-exchange transaction or to assess the exposure to risk. Bid prices and Ask prices need not be quoted, and, even where they are, they will be established by dealers in these instruments and consequently it may be difficult to establish what is a fair price. In regards to transactions in CFDs, forex and precious metals with the Company, the Company is using a trading platform for transactions in CFDs which does not fall into the definition of a recognized exchange as this is not a Multilateral Trading Facility and so do not have the same protection. Foreign Markets
<br/><br/>
9. Foreign markets involve various risks. On request, the Company must provide an explanation of the relevant risks and protections (if any) which will operate in any foreign markets, including the extent to which it will accept liability for any default of a foreign firm through whom it deals. The potential for profit or loss from transactions on foreign markets or in foreign denominated contracts will be affected by fluctuations in foreign exchange rates. Contingent Liability Investment Transactions
<br/><br/>
10. Contingent liability investment transactions, which are margined, require you to make a series of payments against the purchase price, instead of paying the whole purchase price immediately. The Margin requirement will depend on the underlying asset of the instrument. Margin requirements can be fixed or calculated from current price of the underlying instrument, it can be found on the website of the Company. If you trade in futures, Contracts for Differences or sell options, you may sustain a total loss of the funds you have deposited to open and maintain a position. If the market moves against you, you may be called upon to pay substantial additional funds at short notice to maintain the position. If you fail to do so within the time required, your position may be liquidated at a loss and you will be responsible for the resulting deficit. It is noted that the Company will not have a duty to notify the Customer for any Margin Call to sustain a loss making position. Even if a transaction is not margined, it may still carry an obligation to make further payments in certain circumstances over and above any amount paid when you entered the contract. Contingent liability investment transactions which are not traded on or under the rules of a recognised or designated investment exchange may expose you to substantially greater risks. Collateral
<br/><br/>
11. If you deposit collateral as security with the Company, the way in which it will be treated will vary according to the type of transaction and where it is traded. There could be significant differences in the treatment of your collateral depending on whether you are trading on a recognised or designated investment exchange, with the rules of that exchange (and the associated clearing house) applying, or trading off-exchange. Deposited collateral may lose its identity as your property once dealings on your behalf are undertaken. Even if your dealings should ultimately prove profitable, you may not get back the same assets which you deposited, and may have to accept payment in cash. You should ascertain from your firm how your collateral will be dealt with. Commissions and Taxes
<br/><br/>
12. Before you begin to trade, you should make yourself aware of all commissions and other charges for which you will be liable. If any charges are not expressed in monetary terms (but, for example, as a percentage of contract value), you should ensure that you understand the true monetary value of the charges.
<br/><br/>
13. There is a risk that the Customer's trades in any Financial Instruments including derivative instruments may be or become subject to tax and/or any other duty for example because of changes in legislation or his personal circumstances. The Company does not warrant that no tax and/or any other stamp duty will be payable. The Customer is responsible for any taxes and/or any other duty which may accrue in respect of his trades. Suspensions of Trading
<br/><br/>
14. Under certain trading conditions it may be difficult or impossible to liquidate a position. This may occur, for example, at times of rapid price movement if the price rises or falls in one trading session to such an extent that under the rules of the relevant exchange trading is suspended or restricted. Placing a Stop Loss will not necessarily limit your losses to the intended amounts, because market conditions may make it impossible to execute such an Order at the stipulated price. In addition, under certain market conditions the execution of a Stop Loss Order may be worse than its stipulated price and the realized losses can be larger than expected. Clearing House Protections
<br/><br/>
15. On many exchanges, the performance of a transaction by your firm (or third party with whom it is dealing on your behalf) is guaranteed by the exchange or clearing house. However, this guarantee is unlikely in most circumstances to cover you, the Customer, and may not protect you if your firm or another party defaults on its obligations to you. On request, the Company must explain any protection provided to you under the clearing guarantee applicable to any on-exchange derivatives in which you are dealing. There is no clearing house for traditional options, nor normally for off-exchange instruments which are not traded under the rules of a recognised or designated investment exchange. Insolvency
<br/><br/>
16. The Company's insolvency or default, may lead to positions being liquidated or closed out without your consent. In certain circumstances, you may not get back the actual assets which you lodged as collateral and you may have to accept any available payments in cash or by any other method deemed to be appropriate.
<br/><br/>
17. Segregated Funds will be subject to the protections conferred by Applicable Regulations.
<br/><br/>
18. Non-segregated Funds will not be subject to the protections conferred by Applicable Regulations. Non-segregated Funds will not be segregated from the Company's money and will be used in the course of the Company's business, and in the event of the Company's insolvency you will rank as a general creditor.</div>
               <div className='basicTitle'>Third Party Risk</div>
               <div className='basicText'>This notice is provided to you in accordance with applicable legislation.<br/><br/>
1. The Company may pass money received from the Customer to a third party (e.g. a bank, a market, intermediate broker, OTC counterparty or clearing house) to hold or control in order to effect a Transaction through or with that person or to satisfy the Customer's obligation to provide collateral (e.g. initial margin requirement) in respect of a Transaction. The Company has no responsibility for any acts or omissions of any third party to whom it will pass money received from the Customer.
<br/><br/>
2. The third party to whom the Company will pass money may hold it in an omnibus account and it may not be possible to separate it from the Customer's money, or the third party's money. In the event of the insolvency or any other analogous proceedings in relation to that third party, the Company may only have an unsecured claim against the third party on behalf of the Customer, and the Customer will be exposed to the risk that the money received by the Company from the third party is insufficient to satisfy the claims of the Customer with claims in respect of the relevant account. The Company does not accept any liability or responsibility for any resulting losses.
<br/><br/>
3. The Company may deposit Customer money with a depository who may have a security interest, lien or right of set-off in relation to that money.
<br/><br/>
4. A Bank or Broker through whom the Company deals with could have interests contrary to the Customer's Interests.</div>

                </div>
                </div>

                {/* <TradingComponent/> */}
                {/* <StepsToOpenAccount /> */}

        </div>
    );
};

export default RiskPage;
